### ISSUE TITLE
Do not check in node_modules

### ISSUE THREAD

**Issue by jonalmeida** [jarwino/FaceTeX#4]
This is in your `.gitignore` already so I'm not sure why it is there except that it was unintentional. 

Have a look at the MathJax-node [Getting Started](https://github.com/mathjax/MathJax-node#getting-started) section which shows you how to import the library correctly.

See also: [Should I check my `node_modules` folder into git?](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git)

**Comment by jarwino** [comment]
Well, the reason I was checking it in was because MathJax requires the batik to be installed in a subdirectory of the node_modules folder. And even then, there needed to be some editing in the code due to compatability issues.

**Comment by jonalmeida** [comment]
Fair enough. It looks like mathjax-node might be changing that requirement in the future. For now, see the above PR that removes all the other modules which aren't required.
