### ISSUE TITLE
Use environment variables instead of config.json

### ISSUE THREAD

**Issue by jonalmeida** [jarwino/FaceTeX#8]
Using a env variables makes it easier to deploy this app on something like Heroku. You can then add a neat 'Deploy to Heroku' [button](https://devcenter.heroku.com/articles/heroku-button) to your readme.

Also mitigates the problem of unintentionally committing your creds while testing.

**Comment by jonalmeida** [comment]
Nevermind, I decided to just fix this myself.

**Comment by jarwino** [comment]
Much appreciated!
